#!/usr/bin/env bash
#Double the number of webservers
sudo apt update
sudo apt install haproxy -y
sudo sh -c 'echo "\nlisten myserver\n\tbind *:80\n\tbalance roundrobin\n\tserver 455828-web-01 52.3.252.14:80 check\n\tserver 455828-web-02 100.25.2.56:80 check\n" >> /etc/haproxy/haproxy.cfg'
sudo service haproxy restart
